### ISSUE TITLE
Installation guide needed (I have personal errors)

### ISSUE THREAD

**Issue by Andrejki** [prose-intelligence-ltd/Telepathy-Community#40]
Hello. It would be great if there would be a detailed installation guide regarding both ways of installation - via pip or from source from step to step to everyone maybe?

```
Anyway, I have this issue after installing via pip3:
Traceback (most recent call last):
  File "/usr/local/bin/telepathy", line 11, in <module>
    load_entry_point('telepathy==2.3.2', 'console_scripts', 'telepathy')()
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 486, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2867, in load_entry_point
    return ep.load()
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'telepathy'
```
The solution described somewhere to install python panda library, but that was already solved. 

I tried to install it from the source and holly cow, I just can t figure it out. I did `python3 setup.py build` and later `python3 setup.py install` and basically nothing changed, I haven t figured it out to work. How to fix my issues and how to do the installation properly from step 1 to last step? I am not that a newbie, but for this tool installation I am a newbie.

Best regards

**Comment by Andrejki** [comment]
```
/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.1.3 (/home/andrejki/.local/lib/python3.8/site-packages), Requirement.parse('click~=7.1.2'), {'telepathy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/telepathy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/andrejki/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 3.3 (/usr/local/lib/python3.8/dist-packages), Requirement.parse('idna==2.*'), {'httpx'})
```

Ok, I need to change `idna` and `click`, but I don t get the other errors? Is there anyone please?

**Comment by jordanwildon** [comment]
Hi, apologies for the late response. How did you get on with this? If this is still an issue I can write some more detailed installation instructions for you :)
