### ISSUE TITLE
Trouble fetching data from private group

### ISSUE THREAD

**Issue by ComradeWave** [prose-intelligence-ltd/Telepathy-Community#50]
Hello there! I was trying to fetch information from one of my own groups, but if i share the ID of the chat (without the https://t.me/ of course) it just returns an error. (I replaced the id with CHAT_ID, for obvious reasons
```
[!] Performing basic scan
 [-] Fetching details for CHAT_ID...
Traceback (most recent call last):
  File "/usr/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/home/comradewave/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/comradewave/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/comradewave/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/comradewave/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/comradewave/.local/lib/python3.10/site-packages/telepathy/telepathy.py", line 1740, in cli
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/comradewave/.local/lib/python3.10/site-packages/telepathy/telepathy.py", line 444, in main
    entity = await client.get_entity(t)
  File "/home/comradewave/.local/lib/python3.10/site-packages/telethon/client/users.py", line 335, in get_entity
    result.append(await self._get_entity_from_string(x))
  File "/home/comradewave/.local/lib/python3.10/site-packages/telethon/client/users.py", line 574, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "+CHAT_ID"
```

**Comment by inermetso** [comment]
same problem
