### ISSUE TITLE
Session SqlLite bug

### ISSUE THREAD

**Issue by LebidDenys** [prose-intelligence-ltd/Telepathy-Community#51]
Hi! I have problems running telepathy. After the session object is created (I have entered  credentials) I get an error on each of the next runs, error is:
`Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\Scripts\telepathy.exe\__main__.py", line 7, in <module>
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\telepathy\telepathy.py", line 226, in cli
    client = TelegramClient(phone_number, api_id, api_hash)
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\telethon\client\telegrambaseclient.py", line 275, in __init__
    session = SQLiteSession(session)
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\telethon\sessions\sqlite.py", line 47, in __init__
    c = self._cursor()
  File "c:\users\user\pycharmprojects\pythonproject\venv\lib\site-packages\telethon\sessions\sqlite.py", line 242, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file
`.
Would be grateful for any advice.

**Comment by maximus-net** [comment]
I get this exact issue, did you get any response or fix it?

**Comment by acasserole** [comment]
I have the same issue. Any ideas how to fix this?

**Comment by annawarden** [comment]
sqlite3.OperationalError: unable to open database file same problem

**Comment by SjPn** [comment]
HAve the same problem. Do anyone have some fixes?
