### ISSUE TITLE
UnboundLocalError: local variable 'c_replies' referenced before assignment

### ISSUE THREAD

**Issue by Juunjui** [prose-intelligence-ltd/Telepathy-Community#57]
while fetching data from a channel at 99% I got the following message error:
```
on 995: An exception occurred. 'NoneType' object has no attribute 'user_id'
 [-] Progress:  |███████████████████▉⚠︎ (!) 999/1005 [99%] in 23:59.2 (0.69/s) 
Traceback (most recent call last):
  File "/home/[REDCTED]/.local/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/home/[REDCTED]/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/[REDCTED]/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/[REDCTED]/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/[REDCTED]/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/[REDCTED]/.local/lib/python3.9/site-packages/telepathy/telepathy.py", line 1745, in cli
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/[REDCTED]/.local/lib/python3.9/site-packages/telepathy/telepathy.py", line 1360, in main
    c_replies.to_csv(rep_file, sep=";")
UnboundLocalError: local variable 'c_replies' referenced before assignment
```

**Comment by Juunjui** [comment]
happened with another chat at 94%
