### ISSUE TITLE
UnboundLocalError: cannot access local variable 'web_req' where it is not associated with a value

### ISSUE THREAD

**Issue by Ivapol2005** [prose-intelligence-ltd/Telepathy-Community#72]
Traceback (most recent call last):
  File "/home/megagay/.local/bin/telepathy", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/megagay/.local/lib/python3.12/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megagay/.local/lib/python3.12/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/megagay/.local/lib/python3.12/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megagay/.local/lib/python3.12/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megagay/.local/lib/python3.12/site-packages/telepathy/telepathy.py", line 1740, in cli
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/megagay/.local/lib/python3.12/site-packages/telepathy/telepathy.py", line 466, in main
    group_description = web_req["group_description"]
                        ^^^^^^^
UnboundLocalError: cannot access local variable 'web_req' where it is not associated with a value

![lubeuntu](https://github.com/user-attachments/assets/e0bf5072-9c78-4d89-b603-0f19563a7765)

**Comment by Ivapol2005** [comment]
i installed and printed "telepathy -t durov" in cmd

**Comment by 0x773** [comment]
same here
